spring:
  datasource:
    url: jdbc:postgresql://dpg-d3lt09qdbo4c73bdcl20-a:5432/sriharsha?sslmode=require
    username: sriharsha
    password: v2NR7mARcB5egr5FNZHr4CNWf4WH7y4y
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}  # Render automatically sets the PORT environment variable
