spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spamdb
    username: postgres
    password: Harsha@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
